# os: linux
language: node_js
node_js:
  - stable
dist: trusty
sudo: false

cache:
  directories:
  - node_modules

install:
  - npm install -g yarn

before_script: cd servidor

script:
  - npm install
  - yarn lint
  - npm run test
  - cd ../cliente
  - npm install
  - npm run test

on: 
  branch: edgar

# notifications:
#   slack: sytwull:NkXaHBTkYgaYfp5mhS6MDbuu