language: node_js
node_js:
          - "15"
dist: trusty
sudo: false

#branches:
cache:
  directories:
  - node_modules

install:
  - npm install -g yarn

before_script: cd cliente

script:
  - npm install 
  - yarn lint
  - npm run test:unit

after_script: cd ../servidor

script:
  - npm install
  - yarn lint
  - npm run test

on: 
  branch: edgar
