language: node_js
node_js:
          - "9"
dist: trusty
sudo: false

#branches:
#  only:
#  - master

cache:
  directories:
  - node_modules

install:
  - npm install -g yarn

script: 
  - yarn lint

on: 
  branch: nestor
