language: node_js
node_js:
          - "15"
dist: trusty
sudo: false

#branches:
cache:
  directories:
  - node_modules

install:
  - npm install -g yarn

before_script: cd servidor

script: 
  - yarn lint
  - npm run test

on: 
  branch: edgar
